# Generated by Django 5.2.7 on 2025-10-24 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_by', 'email'], name='billing_cli_created_8fca91_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_by', 'phone'], name='billing_cli_created_742136_idx'),
        ),
    ]
