version: '3.8'

services:
  db:
    image: postgres:15
    container_name: invoicing_postgres
    restart: always
    environment:
      POSTGRES_DB: invoicing_db
      POSTGRES_USER: invoicing_user
      POSTGRES_PASSWORD: invoicing_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  